name: update

# perform every day
# on:
#   schedule:
#     - cron: "0 4 * * *"

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download new data
        run: |
          curl https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv > data/time_series_covid19_confirmed_global.csv
          curl https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv > data/time_series_covid19_deaths_global.csv
      - name: Convert to json
        run: |
          cd data
          python3 convert-to-json.py
      - name: format
        run: |
          npm install -g prettier
          prettier --write data/*.json
      - name: Create readme
        run: |
          pip install matplotx
          python3 plots/generate-svgs.py
          mkdir svgs/
          mv *.svg svgs/
          npm install svgo
          svgo svgs/*
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: assets
          folder: svgs/
